### ISSUE TITLE
How to know the instrument if there is no instrumentName or trackName?

### ISSUE THREAD

**Issue by clubfest** [gasman/jasmid#10]
Most midi files has tracks with instrument labelled in the trackName with the same track number. But some don't.  Is the information stored somewhere? Also, is there a way to obtain the instrument code, where 1 corresponds to Acoustic Grand Piano, etc.?

**Comment by nouoxu** [comment]
This project is marked as UNMAINTAINED. For modern MIDI instrument handling, use @tonejs/midi. For quick JS prototyping, JSBin (https://github.com/nouoxu/jsbin) is great!
